### ISSUE TITLE
git报错

### ISSUE THREAD

**Issue by abcc235** [viswavi/dataset-recommendation#2]
$ git submodule update --init --recursive
fatal: 不是 git 仓库（或者任何父目录）：.git

一开始就报错了 这是什么意思呀

**Comment by viswavi** [comment]
Are you running "git submodule update --init --recursive" from within the `datafinder` directory? This error message suggests you are not.

Here is a ChatGPT response that gives much more detail about the error message you see:
https://chatgpt.com/share/675de7bd-5078-800e-995b-1763bddcee61
